#!/bin/bash

APP_NAME="Domotic"
INSTALLER_NAME="Domotic for linux installation script"
VERSION=$(cat ./installation/version)

CONF_DIR="/etc/domotic"
MAIN_CONF_FILE="$CONF_DIR/domotic.conf"

# ottiene il percorso assoluto alla cartella dello script
cd $(dirname $BASH_SOURCE[0])
LOCAL_INSTALLATION_FOLDER=$(pwd)

LOCAL_BIN_FOLDER="/usr/local/bin"
EXECUTABLE_JAR="domotic.jar"
LIBRARIES_FOLDER="domotic_lib"

echo "$INSTALLER_NAME - $VERSION"

if [ ! -h $MAIN_CONF_FILE ]; then
	# configuration file does not exist
	
	if [ ! -d $CONF_DIR ]; then
		# if configuration directory does not exist, create it
		echo "Creating config directory \"$CONF_DIR\" ..."
		mkdir $CONF_DIR
	fi
	
	echo "Installing configuration files ..."

	echo "$MAIN_CONF_FILE"
	cp "$LOCAL_INSTALLATION_FOLDER/conf/domotic_default.conf" $MAIN_CONF_FILE
	
	CONFIGURATION_MESSAGE="A default configuration file has been created in your local directory \"$CONF_DIR\".
	Fill it according to the actual configuration you want to obtain, following the instructions in the configuration file itself.
	You may simply type \"sudo nano $MAIN_CONF_FILE\" in order to edit the configuration file."

else
	#
	echo "Existing configuration file found."
	CONFIGURATION_MESSAGE=""
	
fi


echo "Linking executable jar..."

if [ -h "$LOCAL_BIN_FOLDER/$EXECUTABLE_JAR" ]; then

	# purge local bin directory
	echo "Ppurging local bin directory \"$LOCAL_BIN_FOLDER\""
	rm "$LOCAL_BIN_FOLDER/$EXECUTABLE_JAR"

fi

#
ln -s "$LOCAL_INSTALLATION_FOLDER/$EXECUTABLE_JAR" "$LOCAL_BIN_FOLDER/$EXECUTABLE_JAR"

echo "Linking libraries..."

if [ -h "$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER" ]; then

	#
	echo "Purging libraries folder \"$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER\" ..."
	rm -r "$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER"

fi

ln -s "$LOCAL_INSTALLATION_FOLDER/$LIBRARIES_FOLDER" "$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER"

echo "Type $RESTART_COMMAND to restart $APP_NAME."