#!/bin/bash

APP_NAME="Domotic for linux installation script"
VERSION=$(cat ./installation/version)

CONF_DIR="/etc/domotic"
MAIN_CONF_FILE="$CONF_DIR/domotic.conf"

# ottiene il percorso assoluto alla cartella dello script
cd $(dirname $BASH_SOURCE[0])
LOCAL_INSTALLATION_FOLDER=$(pwd)

LOCAL_BIN_FOLDER="/usr/local/bin"
EXECUTABLE_JAR="domotic.jar"
LIBRARIES_FOLDER="domotic_lib"

echo "$APP_NAME - $VERSION"

if [ ! -d $CONF_DIR ]; then
	#
	echo "Creating config directory \"$CONF_DIR\" ..."
	mkdir $CONF_DIR

else
	#
	echo "Purging configuration directory \"$CONF_DIR\" ..."
	rm $MAIN_CONF_FILE

fi

echo "Installing configuration files ..."

echo "$MAIN_CONF_FILE"
cp "$LOCAL_INSTALLATION_FOLDER/conf/domotic_default.conf" /etc/domotic/domotic.conf

echo "Linking executable jar..."

if [ -h "$LOCAL_BIN_FOLDER/$EXECUTABLE_JAR" ]; then

	# purge local bin directory
	echo "Ppurging local bin directory \"$LOCAL_BIN_FOLDER\""
	rm "$LOCAL_BIN_FOLDER/$EXECUTABLE_JAR"

fi

#
ln -s "$LOCAL_INSTALLATION_FOLDER/$EXECUTABLE_JAR" "$LOCAL_BIN_FOLDER/$EXECUTABLE_JAR"

echo "Linking libraries..."

if [ -h "$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER" ]; then

	#
	echo "Purging libraries folder \"$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER\" ..."
	rm -r "$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER"

fi

ln -s "$LOCAL_INSTALLATION_FOLDER/$LIBRARIES_FOLDER" "$LOCAL_BIN_FOLDER/$LIBRARIES_FOLDER"

echo "Restarting $APP_NAME..."

/etc/init.d/domotic.sh restart
