#!/bin/bash

REPLY=$(domotic-gettcpreply __update_status ${2})

SUBSTRING=${REPLY#*@REPLY?header=STATUS_TEXT_REPLY&body=}
SUBSTRING=${SUBSTRING%&replyto=*}
OUTPUT=$(base64 -d <<< $SUBSTRING)

echo -e "$OUTPUT"

