#!/bin/bash

PID_FILE_DIRECTORY="/tmp"
LOG_FILE_DIRECTORY="/var/log"
EXPECTED_PARAMS="5"

# definizione parametri
# $1 - id del thread di motion
# $2 - framerate della videocamera
# $3 - ingresso sorgente video
# $4 - chiave YT
# $5 - durata massima dello stream

# controlla il numero di parametri passati in argomento, se il numero è errato stampa un messaggio di errore ed esce
if [ $# != $EXPECTED_PARAMS ]; then

	echo "Wrong number of parameters passed. Expected: $EXPECTED_PARAMS, Actual: $#."
	exit 1

fi

# il numero di parametri è corretto

PID_FILE="$PID_FILE_DIRECTORY/domotic-YTLiveStream_$1.pid" # definisce il percorso del file PID
LOG_FILE="$LOG_FILE_DIRECTORY/domotic-TYLiveStream_$1.log" # definisce il percorso del file di log

if [ -f "$PID_FILE" ]; then # esiste già un processo in corso

	echo "PID file found. Killing the process."
	domotic-youtube_livestream_stop $1

fi

# avvia lo streaming in background
nohup domotic-youtube_livestream $1 $2 $3 $4 $5 $6 > $LOG_FILE &

# scrive il numero di processo PID
echo $! > $PID_FILE
echo "$PID_FILE written"

PID=$(cat $PID_FILE)
echo "Process ID is: $PID."
