#!/bin/bash

/etc/init.d/domotic stop
killall -v -g -s SIGKILL java
killall -v -g -s SIGKILL motion

java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address="8000" -jar /usr/local/bin/domotic.jar
