#!/bin/bash

ffmpeg -nostats -loglevel 0 -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -r $2 -i $3 -r $2 -f flv rtmp://a.rtmp.youtube.com/$4 -t $5

domotic-youtube_livestream_stop $1 --nokill
