#!/bin/bash

LIB_DIRECTORY=/var/lib/domotic
TMATE_REPLY=$(tmate -S /tmp/tmate.sock list-sessions)

if [ "$TMATE_REPLY" == "" ]; then

	SESSION_INFO="No active tmate session :("

else

	SSH_LINK=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
	WEB_LINK=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')
	SESSION_INFO="SSH connection string: $SSH_LINK<BR>Click <A HREF=\"$WEB_LINK\">here</A> for web console."

fi

DATE_INFO=$(date)

HTML_PAGE="
<HTML>
	<HEAD>
		<TITLE>$HOST_NAME</TITLE>
	</HEAD>
	<BODY>
		<P>
		Welcome to the tmate connection page!
		</P>
		<P>
		$SESSION_INFO
		</P>
		<P>
		This page was last updated on: $DATE_INFO
		</P>
	</BODY>
</HTML>
"
if [ ! -d $LIB_DIRECTORY ]; then
	mkdir $LIB_DIRECTORY
fi

echo $HTML_PAGE > $LIB_DIRECTORY/tmate-webpage.html

wput -b -q --disable-tls -B -u /var/lib/domotic/tmate-webpage.html ftp://lorenzofailla:fornaci12WebHost@files.000webhost.com:21/public_html/domotic/tmate/index.html