#!/bin/bash

PID_FILE_DIRECTORY="/tmp"
EXPECTED_PARAMS=5

# definizione parametri
# $1 - id del thread di motion
# $2 - framerate della videocamera
# $3 - ingresso sorgente video
# $4 - chiave YT
# $5 - durata massima dello stream

# controlla il numero di parametri passati in argomento, se il numero è errato stampa un messaggio di errore ed esce
if [ $# != EXPECTED_PARAMS ]; then

	echo "Wrong number of parameters passed. Expected: $EXPECTED_PARAMS, Actual: $#."
	exit 1

fi

# il numero di parametri è corretto

PID_FILE="$PID_FILE_PATH/domotic-YTLiveStream_$1.pid" # definisce il percorso del file PID

if [ -f "$PID_FILE" ]; then # esiste già un processo in corso

	echo "PID file found. Killing the process."
	
	# uccide il processo
	kill $(cat $PID_FILE)
	rm $PID_FILE
	echo "Process killed."

fi

# avvia lo streaming in background
domotic-youtube_livestream $1 $2 $3 $4 $5 $6 &

# scrive il numero di processo PID
echo $! > $PID_FILE
PID=$(cat $PID_FILE)
echo "Process $PID started."