#!/bin/bash

PID_FILE="$PID_FILE_PATH/domotic-YTLiveStream_$1.pid" # definisce il percorso del file PID

if [ -f "$PID_FILE" ]; then # esiste già un processo in corso

	echo "PID file found."
	
	if [ $2 != "--nokill" ]; then
	
		# uccide il processo
		kill $(cat $PID_FILE)
	
	fi
	
	rm $PID_FILE
	echo "Process killed."

fi